; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:robot]
board = esp32doit-devkit-v1
build_src_filter = +<robot/>

[env:station]
board = esp32doit-devkit-v1
build_src_filter = +<station/>

[env:feedback]
board = esp32doit-devkit-v1
build_src_filter = +<feedback/>

[env:get_board_address]
board = esp32doit-devkit-v1
build_src_filter = +<utils/get_board_address/>

[env:new_kicker_test]
board = esp32doit-devkit-v1
build_src_filter = +<utils/new_kicker_test/>

[env:test_comm_sender]
board = esp32doit-devkit-v1
build_src_filter = +<utils/test_comm_sender/>

[env:test_comm_receiver]
board = esp32doit-devkit-v1
build_src_filter = +<utils/test_comm_receiver/>

[env:test_kicker_sender]
board = esp32doit-devkit-v1
build_src_filter = +<utils/test_kicker_sender/>

[env:test_kicker_receiver]
board = esp32doit-devkit-v1
build_src_filter = +<utils/test_kicker_receiver/>
