#pragma once

#include <cstdint>

#define VOLTAGE_SENSOR_PIN 34
#define KICKER_PIN 33
#define CHARGE_KICKER_PIN 18
#define DRIBBLER_PIN 32

#define SENSOR_KICKER 14

#define MAX_DRIBBLER 110
#define DRIBBLER_FREQUENCY 50
#define DRIBBLER_MIN_THROTTLE 1048
#define DRIBBLER_MAX_THROTTLE 1952

#define ROBOT_PASSWORD 2400
#define FEEDBACK_PASSWORD 1500

#define MESSAGE_LENGTH_BYTES 200

#define MAX_FAILS_BEFORE_PAUSE 10
#define PAUSE_COOLDOWN_MS 5000
#define PROBE_PERIOD_MS 1500

#define FAILSAFE_MS 300
#define FEEDBACK_INTERVAL_MS 100

#define TIME_AFTER_CHARGE_MS 500
#define TIME_BEFORE_CHARGE_MS 10
#define MIN_CHARGE_TIME_MS 2000
